### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by bigperson** [zanozik/semysms#1]
Hi. I use semysms service very active and I get an error:

> GuzzleHttp\Exception\ClientException: Client error: `POST https://semysms.net/api/3/sms.php` resulted in a `429 Too Many Requests` response: 429 Too Many Requests

How can I postpone sending SMS when I get this error? 
I did not find this function in the standard laravel notifications mechanism.

Sending is done through queues: redis + laravel horizon

**Comment by zanozik** [comment]
Hello,
You could throttle your attempts using [Rate limiting](https://laravel.com/docs/5.6/queues#rate-limiting) if you use Redis to handle your queues.

**Comment by bigperson** [comment]
@zanozik Could you tell me how to use this with the mechanism of notifications?

**Comment by zanozik** [comment]
@bigperson This heavily depends on your redis/queuing configuration. I think you should turn to Laravel forums or QA channels like stackoverflow.com for help.
